"use client";
import {useState} from "react";
import {industries,products} from "@/lib/catalogue";
import {ProductCard} from "./product-card";
import {Icon} from "./site-icon";
const systems=["Bulk Material","Dust Collector","Pneumatic Conveying"];
const types=["Rotary Airlock","Dust Collector","Diverter"];
export function ProductCatalogue({initialQuery="",initialIndustry="",initialSystem=""}:{initialQuery?:string;initialIndustry?:string;initialSystem?:string}){
 const [input,setInput]=useState(initialQuery),[query,setQuery]=useState(initialQuery),[selectedIndustries,setIndustries]=useState<string[]>(initialIndustry?[initialIndustry]:[]),[selectedSystems,setSystems]=useState<string[]>(initialSystem?[initialSystem]:[]),[selectedTypes,setTypes]=useState<string[]>([]),[sort,setSort]=useState("Default"),[showFilters,setShowFilters]=useState(false);
 let results=products.filter(p=>(!query||`${p.name} ${p.summary} ${p.industries.join(" ")}`.toLowerCase().includes(query.toLowerCase()))&&(!selectedIndustries.length||p.industries.some(i=>selectedIndustries.includes(i)))&&(!selectedSystems.length||p.applications.some(s=>selectedSystems.includes(s)))&&(!selectedTypes.length||selectedTypes.includes(p.category)));
 if(sort==="A–Z")results=[...results].sort((a,b)=>a.name.localeCompare(b.name));if(sort==="Z–A")results=[...results].sort((a,b)=>b.name.localeCompare(a.name));
 const groups=[{title:"Rotary Valve Industry",choices:industries.map(i=>i.name),selected:selectedIndustries,set:setIndustries,match:(p:typeof products[number],v:string)=>p.industries.includes(v)},{title:"Rotary Valve System",choices:systems,selected:selectedSystems,set:setSystems,match:(p:typeof products[number],v:string)=>p.applications.includes(v)},{title:"Rotary Valve Type",choices:types,selected:selectedTypes,set:setTypes,match:(p:typeof products[number],v:string)=>p.category===v}];
 function reset(){setIndustries([]);setSystems([]);setTypes([]);setQuery("");setInput("");}
 const active=selectedIndustries.length+selectedSystems.length+selectedTypes.length;
 return <><form className="search-bar" onSubmit={e=>{e.preventDefault();setQuery(input);}}><label className="sr-only" htmlFor="product-search">Search valves by keyword</label><input id="product-search" type="search" value={input} onChange={e=>setInput(e.target.value)} placeholder="Search valves by keyword"/><button className="button" type="submit"><Icon name="search"/> Search</button></form><div className="catalogue-layout"><aside className={`catalogue-sidebar ${showFilters?"open":""}`} id="catalogue-filters" aria-label="Product filters">{groups.map(g=><fieldset className="filter-group" key={g.title}><legend>{g.title}</legend>{g.choices.map(choice=><label className="filter-check" key={choice}><input type="checkbox" checked={g.selected.includes(choice)} onChange={()=>g.set(g.selected.includes(choice)?g.selected.filter(c=>c!==choice):[...g.selected,choice])}/><span>{choice}</span><small>{products.filter(p=>g.match(p,choice)).length}</small></label>)}</fieldset>)}<p className="preview-note">Reference catalogue for layout preview. Final suitability must be confirmed.</p></aside><div><p className="result-count" aria-live="polite">Found {results.length} search results for <strong>“{query||"*"}”</strong></p><div className="result-toolbar">{groups.map(g=><label key={g.title}><span className="sr-only">{g.title}</span><select aria-label={g.title} value={g.selected.length===1?g.selected[0]:""} onChange={e=>g.set(e.target.value?[e.target.value]:[])}><option value="">{g.title} {g.selected.length>1?"Multiple":"All"}</option>{g.choices.map(c=><option key={c} value={c}>{c}</option>)}</select></label>)}<button className="mobile-filter-button" type="button" aria-expanded={showFilters} aria-controls="catalogue-filters" onClick={()=>setShowFilters(!showFilters)}>All filters {active||""}</button><select className="sort-select" aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option>Default</option><option>A–Z</option><option>Z–A</option></select></div>{active||query?<div className="active-filters">{groups.flatMap(g=>g.selected.map(value=><button type="button" className="filter-chip" key={value} onClick={()=>g.set(g.selected.filter(c=>c!==value))}>{value} <Icon name="close"/></button>))}<button className="clear-filters" onClick={reset}>Clear All</button></div>:null}{results.length?<div className="product-grid">{results.map(p=><ProductCard product={p} key={p.slug}/>)}</div>:<div className="empty-state"><h3>No valves match these filters.</h3><p>Try a broader search or clear the selected filters.</p><button className="button button-blue" onClick={reset}>Clear filters</button></div>}</div></div></>;
}
