"use client";
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";
import {products,options} from "@/lib/catalogue";
import {AttachmentButton} from "./site-widgets";
import {Icon} from "./site-icon";
export function ModelGallery(){const [query,setQuery]=useState("");const items=[...products,...options].filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));return <><form className="model-search" onSubmit={e=>e.preventDefault()}><Icon name="search"/><label className="sr-only" htmlFor="model-search">Search by name</label><input id="model-search" type="search" placeholder="Search by name" value={query} onChange={e=>setQuery(e.target.value)}/></form><div className="models-grid">{items.map(p=><div className="model-item" key={p.slug}><AttachmentButton className="model-open" name={`${p.name} 3D model`}><span className="model-image"><Image src={p.image} alt={p.name} fill sizes="(max-width:800px) 45vw,20vw"/></span><strong>{p.name}</strong></AttachmentButton></div>)}</div>{!items.length?<p role="status">No models match your search.</p>:null}</>;}
const steps=["Designed Conveying Rate","Material Bulk Density","Expected Efficiency of Airlock"];
export function SizingWizard(){const [step,setStep]=useState(0);const [values,setValues]=useState(["","","60"]);const number=Number(values[step]);const valid=Number.isFinite(number)&&number>0&&(step!==2||number<=100);const capacity=Number(values[0])/Number(values[1])/(Number(values[2])/100);return <div className="sizing-wizard"><ol className="sizing-steps">{steps.map((label,index)=><li className={step===index?"active":""} key={label}><span>{index+1}</span>{label}</li>)}<li className={step===3?"active":""}><Icon name="sizing"/>Results</li></ol>{step<3?<form className="sizing-form" onSubmit={e=>{e.preventDefault();if(valid)setStep(step+1);}}><div><p className="eyebrow">Step {step+1}</p><h2>{steps[step]}</h2><p>{["Enter the material mass flow rate required by your conveying system.","Enter the bulk density of the material you plan to handle.","Enter the expected filling efficiency as a percentage."][step]}</p><label><span>{steps[step]}</span><div className="sizing-input"><input aria-label={steps[step]} value={values[step]} type="number" min="0.01" step="any" max={step===2?100:undefined} required onChange={e=>setValues(values.map((v,i)=>i===step?e.target.value:v))}/><span>{["pounds per hour (PPH)","lb / ft³","% filling efficiency"][step]}</span></div></label><div className="actions">{step>0?<button className="button button-outline" type="button" onClick={()=>setStep(step-1)}><Icon name="left"/>Back</button>:null}<button className="button" type="submit" disabled={!valid}>Next <Icon name="right"/></button></div></div><aside><h3>Process summary</h3><dl className="spec-grid">{steps.map((s,i)=><div key={s}><dt>{s}</dt><dd>{values[i]||"-"}</dd></div>)}</dl><p className="preview-note">Calculation preview only. This tool does not select or certify a valve size.</p></aside></form>:<section className="sizing-result" aria-live="polite"><p className="eyebrow">Results</p><h2>Estimated displacement requirement</h2><p className="sizing-number">{capacity.toLocaleString("en-US",{maximumFractionDigits:2})} <small>ft³ / hour</small></p><p>Calculated from conveying rate ÷ bulk density ÷ filling efficiency. Confirm the rotor capacity, speed, leakage and operating conditions with engineering before selecting a valve.</p><div className="actions"><button className="button button-outline" onClick={()=>setStep(0)}>Edit inputs</button><Link href="/quote" className="button button-blue">Review with our team <Icon name="right"/></Link></div></section>}</div>;}
