"use client";

import Image from "next/image";
import Link from "next/link";
import {useEffect,useRef,useState, type FormEvent} from "react";
import {articles,brand,faqs,industries,products,type Product} from "@/lib/catalogue";
import {Icon} from "./site-icon";

export function TaxonomyBar(){const [open,setOpen]=useState(false);return <div className="taxonomy-bar"><button className="taxonomy-toggle" aria-expanded={open} aria-controls="taxonomy-items" onClick={()=>setOpen(!open)}>Open navigation <Icon name="down"/></button><div className={`taxonomy-items ${open?"is-open":""}`} id="taxonomy-items"><span className="taxonomy-label">By Industry</span>{industries.map(i=><Link key={i.slug} href={`/solutions/${i.slug}`}><Icon name={i.icon}/><span>{i.name}</span></Link>)}<span className="taxonomy-label">By System</span>{[["Bulk Material","bulk"],["Dust Collector","dust"],["Pneumatic Conveying","conveying"]].map(([name,icon])=><Link href={`/products?system=${encodeURIComponent(name)}`} key={name}><Icon name={icon}/><span>{name}</span></Link>)}</div></div>;}

export function AttachmentButton({children,name,className=""}:{children:React.ReactNode;name:string;className?:string}){const dialog=useRef<HTMLDialogElement>(null);return <><button type="button" className={className} onClick={()=>dialog.current?.showModal()}>{children}</button><dialog className="modal-dialog" ref={dialog} aria-label={name}><button className="modal-close" aria-label="Close dialog" onClick={()=>dialog.current?.close()}><Icon name="close"/></button><h2>{name}</h2><p>This preview does not include a published {name.toLowerCase()} yet.</p><p>Add your own file or model to this item before launching the website.</p><button className="button button-blue" onClick={()=>dialog.current?.close()}>Back to page</button></dialog></>;}

export function FaqList({items=faqs}:{items?:typeof faqs}){return <div className="faq-list">{items.map((item,index)=><details key={item.question} open={index===0}><summary>{item.question}<Icon name="down"/></summary><p>{item.answer}</p></details>)}</div>;}

export function SearchBar({placeholder="Search for a product, blog, video and more"}:{placeholder?:string}){return <form action="/products" className="search-bar"><label className="sr-only" htmlFor="page-search">Search</label><input id="page-search" name="q" type="search" placeholder={placeholder}/><button type="submit" className="button"><Icon name="search"/> Search</button></form>;}

export function HomeHero(){const [slide,setSlide]=useState(0),[paused,setPaused]=useState(false);const slides=[{label:`Welcome to ${brand.name}`,teaser:"Get valve expertise and custom configurations",title:"Let the bulk material flow.",description:"Rotary valves for metering, feeding and airlock applications. Find the configuration for your material, your application and your process.",cta:"Explore our valves",href:"/products"},{label:"Latest Video",teaser:"How shear pin sprockets prevent damage to your valve",title:"How shear pin sprockets prevent damage to your valve",description:"Explore rotary valve components and their role in a reliable conveying system.",cta:"Watch now",href:"/resources/videos"},{label:"Latest Blog",teaser:articles[0].title,title:articles[0].title,description:"",cta:"Read now",href:`/blog/${articles[0].slug}`}];
 useEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){setPaused(true);return;}if(paused)return;const timer=window.setInterval(()=>setSlide(i=>(i+1)%slides.length),10000);return()=>window.clearInterval(timer);},[paused,slides.length]);
 const current=slides[slide];return <section className="home-hero" aria-roledescription="carousel" aria-label="Featured stories"><Image className="hero-background" src="/media/workshop-hero.png" alt="" fill priority sizes="100vw"/><div className="hero-content"><p>{slide>0?current.label:""}</p><h1>{current.title}</h1>{current.description?<p>{current.description}</p>:null}<Link className="hero-cta" href={current.href}><Icon name="right"/><span>{current.cta}</span></Link></div><div className="hero-tabs">{slides.map((s,i)=><button type="button" className={i===slide?"active":""} aria-pressed={i===slide} key={s.label} onClick={()=>{setSlide(i);setPaused(true);}}><small>{s.label}</small>{s.teaser}</button>)}<button className="hero-pause" type="button" aria-label={paused?"Start animation":"Stop animation"} onClick={()=>setPaused(!paused)}><Icon name={paused?"play":"pause"}/></button></div></section>;}

export function IndustryTabs(){const [active,setActive]=useState(0);const visible=Array.from({length:4},(_,i)=>industries[(active+i)%industries.length]);return <><div className="industry-tabs" aria-label="Browse industries">{industries.map((item,index)=><button className={index===active?"active":""} aria-pressed={active===index} key={item.slug} onClick={()=>setActive(index)}><Icon name={item.icon}/>{item.name}</button>)}</div><div className="industry-carousel">{visible.map(item=><article className="industry-card" key={item.slug}><div className="media-frame media-cover"><Image src={`/media/industry-${item.image}.webp`} alt={`${item.name} bulk materials`} fill sizes="(max-width:800px) 100vw,25vw"/></div><div><h3>{item.name}</h3><p>{item.challenge}</p><Link className="button button-blue button-small" href={`/solutions/${item.slug}`}>View valves <Icon name="right"/></Link></div></article>)}</div></>;}

export function ProductGallery({product}:{product:Product}){return <div className="detail-visual"><Image src={product.image} alt={product.name} fill priority sizes="(max-width:800px) 100vw,50vw"/><div className="gallery-controls"><AttachmentButton name="3D model"><Icon name="model"/>View in 3D</AttachmentButton><button className="active" aria-label="Product image selected" aria-pressed="true"><Image src={product.image} alt="" width={60} height={55}/></button></div></div>;}

export function RecommendedProduct({items=products.slice(1,5)}:{items?:Product[]}){const [active,setActive]=useState(0);const p=items[active];return <div className="recommendation"><div className="recommendation-list">{items.map((item,i)=><button className={active===i?"active":""} aria-pressed={active===i} key={item.slug} onClick={()=>setActive(i)}><Image src={item.image} alt="" width={85} height={75}/>{item.name}</button>)}</div><div className="recommendation-image"><Image src={p.image} alt={p.name} fill sizes="(max-width:800px) 100vw,30vw"/></div><div className="recommendation-copy"><div className="recommendation-controls"><button aria-label="Previous recommended valve" onClick={()=>setActive((active-1+items.length)%items.length)}><Icon name="left"/></button><span>RECOMMENDED VALVES ({active+1}/{items.length})</span><button aria-label="Next recommended valve" onClick={()=>setActive((active+1)%items.length)}><Icon name="right"/></button></div><h3>{p.name}</h3><dl className="spec-grid">{p.specifications.map(s=><div key={s.label}><dt>{s.label}</dt><dd>{s.value}</dd></div>)}</dl><Link className="text-link" href={`/products/${p.slug}`}>LEARN MORE <Icon name="right"/></Link></div></div>;}

export function InquiryForm(){const [status,setStatus]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus("Preview complete. Your details have not been sent or stored. Connect your email or CRM before publishing.");}return <form onSubmit={submit}><div className="field-grid">{["First Name","Last Name","Email Address","Company Name","State / Province","Country"].map(label=><label key={label}><span>{label}{label==="Email Address"?" *":""}</span><input name={label} type={label==="Email Address"?"email":"text"} required={label==="Email Address"} autoComplete={label==="Email Address"?"email":undefined}/></label>)}<label className="full"><span>Additional Comments</span><textarea name="comments" rows={4}/></label></div><p className="preview-note">Local preview form — no information is sent.</p><button type="submit" className="button button-blue">Submit <Icon name="right"/></button>{status?<p role="status" className="form-status">{status}</p>:null}</form>;}

export function Newsletter(){const [done,setDone]=useState(false);return <section className="newsletter"><div><p className="eyebrow">Newsletter</p><h2>Stay in the loop.</h2><p>Get rotary valve insights, practical maintenance tips and product updates.</p></div><form onSubmit={e=>{e.preventDefault();setDone(true);}}><div className="field-grid"><label><span>First Name</span><input name="firstName" autoComplete="given-name"/></label><label><span>Last Name</span><input name="lastName" autoComplete="family-name"/></label><label className="full"><span>Email Address *</span><input type="email" name="email" required autoComplete="email"/></label></div><p className="preview-note">Preview only. Subscription service is not connected.</p><button className="button" type="submit">Sign me up <Icon name="right"/></button>{done?<p role="status" className="form-status">Preview complete. No subscription has been created.</p>:null}</form></section>;}
