"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {usePathname} from "next/navigation";
import {brand,industries} from "@/lib/catalogue";
import {Icon} from "./site-icon";

type NavGroup={title:string;links:[string,string][]};
type NavItem={label:string;href:string;groups:NavGroup[];feature:{title:string;copy:string;href:string;cta:string}};
const systemLinks:[string,string][]=[["Bulk Material","/products?system=Bulk%20Material"],["Dust Collector","/products?system=Dust%20Collector"],["Pneumatic Conveying","/products?system=Pneumatic%20Conveying"]];
const navigation:NavItem[]=[
 {label:"Valves",href:"/products",groups:[{title:"Browse",links:[["All Rotary Valves","/products"],["Valve selector guide","/products"]]},{title:"By Industry",links:industries.map(item=>[item.name,`/solutions/${item.slug}`])},{title:"By System",links:systemLinks},{title:"By Type",links:[["Airlock with Metering","/products"],["Metering and Feeding","/products"],["Rotary Airlock","/products"]]}],feature:{title:"Find the right valve",copy:"Start with your material, application and conveying system.",href:"/products",cta:"Browse valves"}},
 {label:"Valve Options",href:"/options",groups:[{title:"Browse",links:[["All options","/options"]]},{title:"Types of options",links:[["Rotors","/options?category=Rotors"],["Kits","/options?category=Kits"],["Accessories","/options?category=Accessories"],["Conveying Equipment","/options?category=Conveying%20Equipment"]]}],feature:{title:"Configure your valve",copy:"Explore rotor, kit and accessory choices for your process.",href:"/options",cta:"View options"}},
 {label:"View in 3D",href:"/models",groups:[{title:"3D Gallery",links:[["View all models","/models"],["Valve gallery","/models"],["Rotor gallery","/models?type=rotors"]]},{title:"Tools",links:[["Valve sizing tool","/sizing"],["Request design assistance","/contact/design-assistance"]]}],feature:{title:"Explore configurations",copy:"Use the gallery to compare equipment before speaking with the team.",href:"/models",cta:"Open gallery"}},
 {label:"About",href:"/about",groups:[{title:"About Dongxin",links:[["The company","/about#company"],["The people","/about#people"],["The facilities","/about#facilities"]]},{title:"Work with us",links:[["Contact the team","/contact"],["Request a quote","/quote"]]}],feature:{title:"Built around your process",copy:"Learn how the team supports selection, configuration and application planning.",href:"/about",cta:"About us"}},
 {label:"Resources",href:"/resources",groups:[{title:"Downloads",links:[["All downloads","/resources/downloads"],["Technical drawings","/resources/technical-drawings"],["Datasheets","/resources/downloads"]]},{title:"Reference",links:[["Glossary","/resources/glossary"],["Videos","/resources/videos"],["Valve sizing tool","/sizing"]]}],feature:{title:"Technical resources",copy:"Find product information, drawings and practical application guidance.",href:"/resources",cta:"Browse resources"}},
 {label:"Blog",href:"/blog",groups:[{title:"Blog",links:[["All articles","/blog"],["Quick Cleaning","/blog?category=Quick%20Cleaning"],["Customization","/blog?category=Customization"],["Maintenance","/blog?category=Maintenance"]]},{title:"FAQs",links:[["All FAQs","/support?category=FAQs"],["Technical support","/support?category=FAQs"],["Safety and reliability","/support?category=FAQs"]]}],feature:{title:"Practical valve knowledge",copy:"Read selection, cleaning and maintenance guidance for bulk material systems.",href:"/blog",cta:"Visit blog"}},
 {label:"Tech Support",href:"/support",groups:[{title:"Support sections",links:[["Videos","/support?category=Videos"],["Technical drawings","/support?category=Tech%20Drawings"],["FAQs","/support?category=FAQs"],["Articles","/support?category=Articles"]]},{title:"Need help?",links:[["Contact technical support","/contact"],["Request replacement planning","/contact/replacement"]]}],feature:{title:"Keep your process moving",copy:"Find support resources or share a service question with the team.",href:"/support",cta:"Get support"}},
];

export function SiteHeader(){
 const path=usePathname();
 const [submenu,setSubmenu]=useState<string|null>(null);
 const [menu,setMenu]=useState(false),[search,setSearch]=useState(false),[compact,setCompact]=useState(false),[contrast,setContrast]=useState(false);
 useEffect(()=>{const onScroll=()=>setCompact(window.scrollY>90);onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll);},[]);
 useEffect(()=>{document.documentElement.classList.toggle("high-contrast",contrast);return()=>document.documentElement.classList.remove("high-contrast");},[contrast]);
 function close(){setMenu(false);setSearch(false);setSubmenu(null);}
 return <><a className="skip-link" href="#main-content">Skip to main content</a><header className={`site-header ${compact?"is-compact":""}`} onKeyDown={event=>{if(event.key==="Escape")close();}}>
 <Link href="/" className="brand" aria-label={`${brand.name} home`} onClick={close}><strong>{brand.shortName}</strong><span>{brand.descriptor}</span></Link>
 <nav className="utility-nav" aria-label="Site tools"><button aria-label="Toggle high contrast" aria-pressed={contrast} onClick={()=>setContrast(!contrast)}><Icon name="contrast"/></button><Link href="/contact/representatives" onClick={close}>Locate a Rep</Link><Link href="/quote" onClick={close}>Request a Quote</Link><Link href="/contact" onClick={close}>Contact Us</Link><Link className="utility-contact" href="/contact" onClick={close}><Icon name="phone"/> TALK TO OUR TEAM</Link></nav>
 <div className="header-actions"><Link className="mobile-contact" href="/contact" aria-label="Contact our team" onClick={close}><Icon name="phone"/></Link><button className="search-toggle" aria-label="Open search" aria-expanded={search} aria-controls="header-search" onClick={()=>{setSearch(!search);setMenu(false);}}><Icon name={search?"close":"search"}/></button><button className="menu-toggle" aria-label={menu?"Close navigation":"Open navigation"} aria-expanded={menu} aria-controls="main-navigation" onClick={()=>{setMenu(!menu);setSearch(false);}}><Icon name={menu?"close":"menu"}/></button></div>
 <nav id="main-navigation" className={`primary-nav ${menu?"is-open":""}`} aria-label="Main navigation">{navigation.map(item=><div className={`nav-item ${submenu===item.href?"submenu-open":""}`} key={item.href}><Link href={item.href} onClick={close} className={path.startsWith(item.href)?"active":""}><span className="nav-label">{item.label}</span></Link><button className="nav-submenu-toggle" aria-label={`Toggle ${item.label} submenu`} aria-expanded={submenu===item.href} aria-controls={`submenu-${item.href.slice(1)}`} onClick={()=>setSubmenu(submenu===item.href?null:item.href)}><Icon name="down"/></button><div className="nav-dropdown" id={`submenu-${item.href.slice(1)}`}><div className="nav-dropdown-inner"><div className="nav-dropdown-groups">{item.groups.map(group=><section key={group.title}><strong>{group.title}</strong>{group.links.map(([label,href])=><Link href={href} key={`${group.title}-${label}`} onClick={close}>{label}</Link>)}</section>)}</div><Link className="nav-dropdown-feature" href={item.feature.href} onClick={close}><span>{item.feature.title}</span><p>{item.feature.copy}</p><b>{item.feature.cta} <Icon name="right"/></b></Link></div></div></div>)}</nav>
 {search?<form id="header-search" className="header-search" action="/products" onSubmit={close}><label className="sr-only" htmlFor="global-search">Search the product catalogue</label><input id="global-search" name="q" type="search" placeholder="Search valves, options and resources" autoFocus/><button className="button" type="submit"><Icon name="search"/> Search</button></form>:null}
 </header></>;
}
