import Image from "next/image";
import Link from "next/link";
import {articles,industries,products} from "@/lib/catalogue";
import {Icon} from "./site-icon";
import {AttachmentButton} from "./site-widgets";

export function Media({src,alt,cover=false,priority=false}:{src:string;alt:string;cover?:boolean;priority?:boolean}){return <div className={`media-frame ${cover?"media-cover":""}`}><Image src={src} alt={alt} fill sizes="(max-width:800px) 100vw,50vw" priority={priority}/></div>;}
export function HelpSection(){return <section className="help-section"><h2>Need help choosing the right valve?</h2><p className="lead">Get in touch to discuss the best match for your material and process requirements.</p><div className="help-grid"><article className="help-main"><div><p className="eyebrow">Rotary valve sizing tool</p><h3>Size your valve in 3 steps</h3><Link className="button button-blue" href="/sizing">Size your valve <Icon name="right"/></Link></div><div className="help-image"><Image src="/media/sizing.webp" alt="Rotary valve sizing illustration" fill sizes="(max-width:800px) 100vw,35vw"/></div></article><div className="help-stack"><article className="help-small"><Icon name="drawing"/><div><h3>In-house design services</h3><Link className="button button-blue button-small" href="/contact/design-assistance">Get design help <Icon name="right"/></Link></div></article><article className="help-small"><Icon name="download"/><div><h3>View rotary valve technical drawings</h3><Link className="button button-blue button-small" href="/resources/technical-drawings">See drawings <Icon name="right"/></Link></div></article></div></div></section>;}
export function EditorialCards({count=3}:{count?:number}){return <div className="editorial-cards">{articles.slice(0,count).map(a=><article className="editorial-card" key={a.slug}><Link href={`/blog/${a.slug}`} tabIndex={-1} aria-hidden="true"><Media src={a.image} alt=""/></Link><div className="editorial-card-body"><p className="eyebrow">Latest blog</p><h3><Link href={`/blog/${a.slug}`}>{a.title}</Link></h3><p>{a.summary}</p><Link className="button button-blue button-small" href={`/blog/${a.slug}`}>Read more <Icon name="right"/></Link></div></article>)}</div>;}
export function PromoRow(){return <div className="promo-row"><article className="promo-card"><p className="eyebrow">Product highlight</p><h3>Go ahead, make your valve</h3><p>Explore rotors, kits and accessories for your material handling application.</p><Link href="/options">VIEW OPTIONS <Icon name="right"/></Link></article><article className="promo-card"><p className="eyebrow">Latest blog</p><h3>{articles[0].title}</h3><p>{articles[0].summary}</p><Link href={`/blog/${articles[0].slug}`}>READ MORE <Icon name="right"/></Link></article><article className="promo-card"><p className="eyebrow">Videos & resources</p><h3>See how rotary valves work</h3><p>Browse maintenance guides, application resources and product documentation.</p><Link href="/resources/videos">WATCH VIDEOS <Icon name="play"/></Link></article></div>;}
export function IndustryIcons(){return <div className="industry-icons">{industries.map(i=><Link href={`/solutions/${i.slug}`} key={i.slug}><Icon name={i.icon}/>{i.name}</Link>)}</div>;}
export function SidebarPromos(){return <><article className="sidebar-promo"><h3>Explore in our 3D gallery.</h3><Media src="/media/models.webp" alt="Rotary valve product view"/><Link className="button button-blue button-small" href="/models"><Icon name="model"/> View in 3D</Link></article><article className="sidebar-promo"><h3>Try the valve sizing tool</h3><Media src="/media/sizing.webp" alt="Valve sizing"/><Link className="button button-blue button-small" href="/sizing">Size a valve <Icon name="right"/></Link></article><article className="sidebar-promo"><h3>Related valves</h3><Media src={products[9].image} alt={products[9].name}/><h3>{products[9].name}</h3><Link className="button button-blue button-small" href={`/products/${products[9].slug}`}>Read more <Icon name="right"/></Link></article></>;}
export function ContactNav(){return <nav className="subnav" aria-label="Contact navigation">{[["Map & General Inquiries","/contact"],["Locate a Representative","/contact/representatives"],["Request a Quote","/quote"],["I Need Airlock Consulting","/contact/consulting"],["Get Design Assistance","/contact/design-assistance"],["Request Replacement Valve","/contact/replacement"]].map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</nav>;}
export function ResourceCard({title,type="Datasheet"}:{title:string;type?:string}){return <article className="resource-card"><Icon name={type==="Technical Drawing"?"drawing":"document"}/><div><h3>{title}</h3><p>{type} and product information for your application.</p><AttachmentButton name={`${title} ${type}`}>Download <Icon name="right"/></AttachmentButton></div></article>;}
