import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {EditorialPage} from "@/components/editorial-page";
const pages={
 accessibility:{eyebrow:"Accessibility",title:"Accessible information starts with a clear digital experience.",lead:"Dongxin Machinery can publish its approved accessibility statement, service accommodations and contact method here.",cards:[{title:"Website access",copy:"Use semantic pages, keyboard-friendly controls and responsive content to make information easier to reach.",icon:"support"},{title:"Document requests",copy:"Provide an accessible alternative when a published document cannot be used as supplied.",icon:"document"},{title:"Contact pathway",copy:"Give visitors a direct way to request help or report an accessibility issue.",icon:"person",href:"/contact"}]},
 "industry-associations":{eyebrow:"Industry associations",title:"Professional connections that support better project conversations.",lead:"Publish only the associations, memberships and partnerships verified by Dongxin Machinery.",cards:[{title:"Technical exchange",copy:"Share approved technical resources and industry events.",icon:"drawing",href:"/resources"},{title:"Application knowledge",copy:"Connect customers to practical material-handling guidance.",icon:"bulk",href:"/blog"},{title:"Project support",copy:"Bring the right stakeholders into the application review.",icon:"support",href:"/contact"}]},
 "trade-associations":{eyebrow:"Trade associations",title:"Collaboration around the material-handling process.",lead:"Use this page to present current, verified professional memberships and industry participation.",cards:[{title:"Current memberships",copy:"Show only organizations approved for publication by Dongxin Machinery.",icon:"person"},{title:"Resources",copy:"Provide product documentation and technical references for project teams.",icon:"document",href:"/resources"},{title:"Talk with us",copy:"Discuss your project requirements with the Dongxin team.",icon:"chat",href:"/contact"}]}
} as const;
type Key=keyof typeof pages;
export function generateStaticParams(){return Object.keys(pages).map(section=>({section}));}
export async function generateMetadata({params}:{params:Promise<{section:string}>}):Promise<Metadata>{const {section}=await params;return {title:pages[section as Key]?.eyebrow??"About"};}
export default async function AboutSection({params}:{params:Promise<{section:string}>}){const {section}=await params;const page=pages[section as Key];if(!page)notFound();return <EditorialPage {...page} image="/media/workshop-hero.png" note="Company-specific memberships and policies will be published after Dongxin Machinery approves them."/>;}
