import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {products,articles} from "@/lib/catalogue";
import {Media,ResourceCard,PromoRow} from "@/components/site-blocks";
import {AttachmentButton} from "@/components/site-widgets";
import {Icon} from "@/components/site-icon";
const kinds:Record<string,string>={videos:"Videos",downloads:"Downloads","technical-drawings":"Technical Drawings",glossary:"Glossary"};
type Props={params:Promise<{kind:string}>};
export function generateStaticParams(){return Object.keys(kinds).map(kind=>({kind}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {kind}=await params;return {title:kinds[kind]??"Resources"};}
export default async function ResourceCategory({params}:Props){const {kind}=await params;const title=kinds[kind];if(!title)notFound();return <div className="shell"><h1 className="page-heading">{title}</h1><nav className="tabs" aria-label="Resource categories">{Object.entries(kinds).map(([slug,label])=><Link href={`/resources/${slug}`} className={kind===slug?"active":""} key={slug}>{label}</Link>)}</nav>{kind==="videos"?<><section className="resource-feature"><div className="resource-video"><Media src="/media/rotor-01.webp" alt="Valve components"/><AttachmentButton className="video-play" name="Featured video"><Icon name="play"/></AttachmentButton></div><div className="resource-feature-copy"><span>FEATURED</span><h2>Explore rotary valve components</h2><p>Application and maintenance information for your material handling equipment.</p><details><summary>Transcript</summary><p>A video and transcript can be added here when your own media is ready.</p></details></div></section><section className="resource-sections"><h2>More Videos</h2><div className="editorial-cards">{articles.map(a=><article className="editorial-card" key={a.slug}><Media src={a.image} alt=""/><div className="editorial-card-body"><h3>{a.title}</h3><AttachmentButton className="text-link" name={a.title}>Watch video <Icon name="play"/></AttachmentButton></div></article>)}</div></section></>:kind==="glossary"?<section className="resource-sections glossary-list">{[["Airlock","Equipment used to separate areas with different pressure conditions while transferring material."],["Bulk Density","The mass of a bulk material divided by the volume it occupies, including the spaces between particles."],["Conveying Rate","The quantity of material transported over a given period, expressed with a defined mass or volume unit."],["Rotor","The rotating component inside a rotary valve that carries material through the housing."],["Shaft Seal","A sealing arrangement at the point where a rotating shaft passes through the housing."]].map(([term,definition])=><section key={term}><h2>{term}</h2><p>{definition}</p></section>)}</section>:<section className="resource-sections"><div className="resource-cards">{products.slice(0,16).map(p=><ResourceCard title={p.name} type={kind==="downloads"?"Datasheet":"Technical Drawing"} key={p.slug}/>)}</div></section>}<PromoRow/></div>;}
