import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {notFound} from "next/navigation";
import {articles,brand} from "@/lib/catalogue";
import {EditorialCards} from "@/components/site-blocks";
import {Icon} from "@/components/site-icon";
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;return {title:articles.find(a=>a.slug===slug)?.title??"Article"};}
export default async function ArticlePage({params}:Props){const {slug}=await params;const article=articles.find(a=>a.slug===slug);if(!article)notFound();const next=articles[(articles.indexOf(article)+1)%articles.length];return <article className="article-page"><div className="article-inner"><header className="article-heading"><div><h1>{article.title}</h1><p>Application notes by <strong>{brand.name}</strong></p></div><Link className="button button-blue button-small" style={{alignSelf:"start"}} href={`/blog/${next.slug}`}>Next <Icon name="right"/></Link></header><div className="article-body"><div className="article-image"><Image src={article.image} alt={article.title} fill sizes="(max-width:800px) 100vw,40vw" priority/></div><p>{article.summary}</p><p>Every material handling application starts with a different set of requirements. The characteristics of the material, the equipment around the valve and the conditions inside the process all influence the configuration.</p><h2>Start with your process</h2><p>Gather the material description, required flow rate, bulk density, operating temperature and pressure. Include drawings of the available installation space and the equipment above and below the valve.</p><h2>Compare the configuration options</h2><p>Review the housing material, rotor arrangement, shaft seals, drive and accessories as a complete system. Cleaning access, maintenance procedures and material compatibility are useful points to discuss with your engineering team.</p><h2>Confirm the final details</h2><p>Use verified product documentation and application-specific engineering advice before making a final selection. Published ratings must match the exact configuration being supplied.</p><Link href="/quote" className="button button-blue">Discuss your application <Icon name="right"/></Link><p className="preview-note">Editorial preview. Replace with your approved application article before publication.</p></div><section className="section"><h2>Related articles</h2><EditorialCards/></section></div></article>;}
